
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- DUOLOGI & CUIDADO CAPILAR (Oferta Acondicionadores) ---
    {
        id: 44961,
        name: "Acondicionador Rico Reparador Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44961%2F44961_1.png',
        description: "Acondicionador nutritivo que repara y protege el cabello dañado reduciendo la rotura. Enriquecido con Queratina y Lípidos de Avena. ¡Oferta especial!",
        howToUse: "Aplicar sobre el cabello húmedo de medios a puntas. Dejar actuar y aclarar.",
        stock: 100,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.7,
        reviewCount: 55,
    },
    {
        id: 44960,
        name: "Acondicionador Ligero Voluminizador DUOLOGI",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44960%2F44960_1.png',
        description: "Acondicionador ligero que hidrata y desenreda cabellos finos sin apelmazar, aportando volumen.",
        howToUse: "Aplicar en cabello limpio y húmedo de medios a puntas y aclarar.",
        stock: 85,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.6,
        reviewCount: 42,
    },
    {
        id: 44964,
        name: "Serum Sellador DUOLOGI",
        brand: "DUOLOGI",
        price: 10.99,
        regularPrice: 17.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44964%2F44964_1.png',
        description: "Serum sellador para puntas abiertas que suaviza y protege el cabello.",
        stock: 45,
        category: 'hair',
        rating: 4.6,
        reviewCount: 313,
    },
    {
        id: 44966,
        name: "Exfoliante Purificante para Cuero Cabelludo DUOLOGI",
        brand: "DUOLOGI",
        price: 8.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44966%2F44966_1.png',
        description: "Exfoliante que purifica el cuero cabelludo, eliminando impurezas y residuos.",
        stock: 50,
        category: 'hair',
        rating: 4.8,
        reviewCount: 527,
    },
    {
        id: 44951,
        name: "Champú Purificante Anti-Caspa DUOLOGI",
        brand: "DUOLOGI",
        price: 8.99,
        regularPrice: 13.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44951%2F44951_1.png',
        description: "Champú eficaz contra la caspa que purifica y refresca el cuero cabelludo.",
        stock: 60,
        category: 'hair',
        rating: 4.7,
        reviewCount: 491,
    },
    {
        id: 44955,
        name: "Champú Anti-Caída DUOLOGI",
        brand: "DUOLOGI",
        price: 8.99,
        regularPrice: 13.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44955%2F44955_1.png',
        description: "Fortalece el cabello frágil y ayuda a reducir la caída del cabello.",
        stock: 70,
        category: 'hair',
        rating: 4.7,
        reviewCount: 988,
    },
    {
        id: 44956,
        name: "Champú Protector del Color DUOLOGI",
        brand: "DUOLOGI",
        price: 8.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44956%2F44956_1.png',
        description: "Protege la intensidad del color y prolonga su brillo.",
        stock: 40,
        category: 'hair',
        rating: 4.7,
        reviewCount: 347,
    },
    {
        id: 44962,
        name: "Champú en Seco Anti-Grasa DUOLOGI",
        brand: "DUOLOGI",
        price: 8.99,
        regularPrice: 15.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44962%2F44962_1.png',
        description: "Revitaliza el cabello entre lavados, absorbiendo el exceso de grasa.",
        stock: 35,
        category: 'hair',
        rating: 4.8,
        reviewCount: 806,
    },
    {
        id: 46492,
        name: "Masajeador para Cuero Cabelludo DUOLOGI",
        brand: "DUOLOGI",
        price: 5.29,
        regularPrice: 7.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46492%2F46492_1.png',
        description: "Estimula la circulación del cuero cabelludo para un cabello más sano.",
        stock: 100,
        category: 'accessories',
        rating: 4.8,
        reviewCount: 364,
    },
    {
        id: 44990,
        name: "Crema Capilar Dual Sin Aclarado DUOLOGI",
        brand: "DUOLOGI",
        price: 4.99,
        regularPrice: 9.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44990%2F44990_1.png',
        description: "Crema versátil para hidratar y proteger el cabello sin necesidad de aclarado.",
        stock: 55,
        category: 'hair',
        rating: 4.5,
        reviewCount: 56,
    },

    // --- LOVE NATURE & CUIDADO PERSONAL ---
    {
        id: 47440,
        name: "Gel de Ducha con Fresa Orgánica Simple Joys Love Nature",
        brand: "Love Nature",
        price: 4.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47440%2F47440_1.png',
        description: "Edición Especial. Gel de ducha refrescante con delicioso aroma a fresa orgánica.",
        stock: 80,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 202,
    },
    {
        id: 46987,
        name: "Gel de Ducha con Mango Orgánico Simple Joys Love Nature",
        brand: "Love Nature",
        price: 7.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46987%2F46987_1.png',
        description: "Gel de ducha con extracto de mango orgánico, suave y afrutado.",
        stock: 75,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 731,
    },
    {
        id: 47009,
        name: "Gel de Ducha con Aloe Vera Orgánico Simple Joys Love Nature",
        brand: "Love Nature",
        price: 7.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47009%2F47009_1.png',
        description: "Gel de ducha hidratante y calmante con Aloe Vera orgánico.",
        stock: 60,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 717,
    },
    {
        id: 41308,
        name: "Tratamiento Hot Oil para Cabello Seco con Trigo y Coco",
        brand: "Love Nature",
        price: 3.29,
        regularPrice: 6.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41308%2FES%2F41308_1.png',
        description: "Tratamiento intensivo de aceite caliente para nutrir el cabello seco.",
        stock: 100,
        category: 'hair',
        rating: 4.7,
        reviewCount: 615,
    },
    {
        id: 41338,
        name: "Crema de Manos Nutritiva con Aceite de Coco Orgánico",
        brand: "Love Nature",
        price: 4.99,
        regularPrice: 11.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41338%2FES%2F41338_1.png',
        description: "Nutrición intensa para manos secas con las propiedades del coco.",
        stock: 50,
        category: 'personal-care',
        rating: 4.8,
        reviewCount: 700,
    },
    {
        id: 41488,
        name: "Crema de Ducha Nutritiva con Manteca de Cacao y Aceite de Coco",
        brand: "Love Nature",
        price: 5.99,
        regularPrice: 8.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41488%2FES%2F41488_1.png',
        description: "Ducha cremosa y nutritiva que deja la piel suave e hidratada.",
        stock: 45,
        category: 'personal-care',
        rating: 4.7,
        reviewCount: 352,
    },
    {
        id: 41490,
        name: "Loción Corporal Nutritiva con Manteca de Cacao y Aceite de Coco",
        brand: "Love Nature",
        price: 15.99,
        regularPrice: 21.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41490%2F41490_1.png',
        description: "Loción corporal rica y nutritiva para pieles extra secas.",
        stock: 40,
        category: 'personal-care',
        rating: 4.8,
        reviewCount: 1173,
    },
    {
        id: 41505,
        name: "Loción Corporal Energizante con Menta y Frambuesa",
        brand: "Love Nature",
        price: 11.99,
        regularPrice: 22.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41505%2FES%2F41505_1.png',
        description: "Loción corporal ligera y energizante que despierta tus sentidos.",
        stock: 45,
        category: 'personal-care',
        rating: 4.8,
        reviewCount: 830,
    },
     {
        id: 47202,
        name: "Crema de Manos y Uñas Protectora con Fruta de la Pasión",
        brand: "Love Nature",
        price: 4.99,
        regularPrice: 11.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47202%2F47202_1.png',
        description: "Protege e hidrata manos y uñas con un exótico aroma.",
        stock: 65,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 713,
    },

    // --- ESSENSE & CO ---
    {
        id: 46642,
        name: "Jabón Líquido Manos y Cuerpo Limón y Verbena Essense & Co",
        brand: "Essense&Co.",
        price: 14.99,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46642%2F46642_1.png',
        description: "Elegante jabón líquido con aceites naturales de limón y verbena.",
        stock: 30,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 1139,
    },
    {
        id: 46731,
        name: "Recambio Jabón Líquido Limón y Verbena Essense & Co",
        brand: "Essense&Co.",
        price: 8.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46731%2F46731_1.png',
        description: "Recambio sostenible para tu jabón favorito.",
        stock: 40,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 1305,
    },
    {
        id: 45799,
        name: "Jabón Líquido Manos y Cuerpo Amapola y Vainilla Essense & Co",
        brand: "Essense&Co.",
        price: 14.99,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45799%2F45799_1.png',
        description: "Limpieza suave con aroma floral y cálido.",
        stock: 25,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 700,
    },
    {
        id: 45800,
        name: "Loción Hidratante Manos y Cuerpo Amapola y Vainilla Essense & Co",
        brand: "Essense&Co.",
        price: 15.99,
        regularPrice: 21.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45800%2F45800_1.png',
        description: "Hidratación lujosa que deja la piel sedosa.",
        stock: 25,
        category: 'personal-care',
        rating: 4.8,
        reviewCount: 349,
    },
    {
        id: 47450,
        name: "Recambio Jabón Líquido Amapola y Vainilla Essense & Co",
        brand: "Essense&Co.",
        price: 8.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47450%2F47450_1.png',
        description: "Opción ecológica para rellenar tu dispensador.",
        stock: 35,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 0,
    },

    // --- CUIDADO ESPECÍFICO Y OTROS ---
    {
        id: 36151,
        name: "Crema Universal con Aceite de Grosella Negra",
        brand: "Tender Care",
        price: 7.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F36151%2F36151_1.png',
        description: "El bálsamo clásico con un toque afrutado de grosella negra.",
        stock: 100,
        category: 'skincare',
        rating: 4.9,
        reviewCount: 2226,
    },
     {
        id: 35890,
        name: "Acondicionador Reparador Beautanicals",
        brand: "Beautanicals",
        price: 15.99,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F35890%2F35890_1.png',
        description: "Fórmula con minerales esenciales y extracto de madreselva sueca.",
        stock: 20,
        category: 'hair',
        rating: 4.8,
        reviewCount: 291,
    },
    {
        id: 38601,
        name: "Aceite Protección Capilar Eleo",
        brand: "Eleo",
        price: 19.99,
        regularPrice: 26.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38601%2F38601_1.png',
        description: "Aceite lujoso con Argán y Rosas para proteger y nutrir el cabello.",
        stock: 30,
        category: 'hair',
        rating: 4.8,
        reviewCount: 921,
    },
    {
        id: 38602,
        name: "Aceite Capilar Reparador de Noche Eleo",
        brand: "Eleo",
        price: 14.99,
        regularPrice: 26.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38602%2F38602_1.png',
        description: "Nutrición nocturna intensa para despertar con un cabello sublime.",
        stock: 28,
        category: 'hair',
        rating: 4.9,
        reviewCount: 585,
    },
    {
        id: 46968,
        name: "Crema para Manos y Cuerpo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 18.00,
        regularPrice: 24.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46968%2F46968_1.png',
        description: "La legendaria crema nutritiva con extractos orgánicos de leche y miel.",
        stock: 80,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 3560,
    },
    {
        id: 46969,
        name: "Exfoliante Corporal de Azúcar Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 11.99,
        regularPrice: 17.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46969%2F46969_1.png',
        description: "Exfoliante de azúcar que deja la piel suave y radiante.",
        stock: 60,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 981,
    },
    {
        id: 46970,
        name: "Crema de Ducha Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 15.00,
        regularPrice: 19.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46970%2F46970_1.png',
        description: "Limpieza cremosa que mima tu piel.",
        stock: 50,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 1203,
    },
    {
        id: 46971,
        name: "Jabón en Barra Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 4.79,
        regularPrice: 6.50,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46971%2F46971_1.png',
        description: "Jabón cremoso con la icónica fragancia de leche y miel.",
        stock: 100,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 773,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia Chipre Floral Amaderada que deja una estela hipnótica y duradera. Perfecto para la noche.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 47677,
        name: "Cepillo Estilizador Glam On-the-Go",
        brand: "StylerPRO",
        price: 64.99,
        regularPrice: 80.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47677%2F47677_1.png",
        description: "Cepillo alisador compacto para retocar tu peinado en cualquier lugar. ¡Novedad!",
        stock: 15,
        category: 'hair',
        tag: 'NOVEDAD',
        rating: 4.7,
        reviewCount: 70,
    },
    {
        id: 47878,
        name: "Esponja de Baño Lather Lily",
        brand: "Love Nature",
        price: 7.49,
        regularPrice: 9.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47878%2F47878_1.png",
        description: "Esponja de baño que genera abundante espuma para una ducha placentera.",
        stock: 50,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.6,
        reviewCount: 209,
    }
];
